class ResponseCode:
    SUCCESSFUL = 0
    FAILED = 1

    BAD_REQUEST = 3


class AuthenticationResponse:
    UN_AUTHENTICATED_USER = 30
    INVALID_SOURCE = 31
    PERMISSION_DENIED = 32


class ExplorationResponse:
    SOURCE_IS_OFFLINE = 40
    EXPLORER_IS_OFFLINE = 41

    ANSWER_PERMISSION_GRANTED = 41
    ANSWER_PERMISSION_DENIED = 42

    INVALID_ANSWER = 43
    INVALID_SESSION = 44
